/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chigoo_wifilocation_ChigooWifiInfo */

#ifndef _Included_com_chigoo_wifilocation_ChigooWifiInfo
#define _Included_com_chigoo_wifilocation_ChigooWifiInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
