/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chigoo_wifilocation_ChigooWifiLocation */

#ifndef _Included_com_chigoo_wifilocation_ChigooWifiLocation
#define _Included_com_chigoo_wifilocation_ChigooWifiLocation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chigoo_wifilocation_ChigooWifiLocation
 * Method:    Locate
 * Signature: (Ljava/util/ArrayList;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chigoo_wifilocation_ChigooWifiLocation_Locate
        (JNIEnv *, jobject, jobject obj,jobject accelerometer);

#ifdef __cplusplus
}
#endif
#endif
